name: Gradle test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  checks: write
  contents: read

jobs:
  gradle-test:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
